port: 4003
incremental: true

defaults:
  -
    scope:
      path: "recipes/breakfast"
      type: "pages"
    values:
      categories: ["breakfast", "recipes"]
  -
    scope:
      path: "recipes/desserts"
      type: "pages"
    values:
      categories: ["desserts", "recipes"]